### ISSUE TITLE
Does not mine, only displays "Warming Up"

### ISSUE THREAD

**Issue by lukespragg** [7THStage/idigdoge#10]
Server updated and working now, but the site does not mine, it only displays it as "Warming Up", other than that everything looks normal. No errors in the log file, only the output in the console as shown below.

```
[INFO] 2014-02-26T17:43:34.640Z 29392 Using Development Environment
[INFO] 2014-02-26T17:43:34.656Z 29392 Redis Is Ready
GET / 304 264ms
GET /public/style.css?2 304 8ms
GET /public/main.js?2 304 6ms
GET /api/balance 304 6ms
GET /api/work 304 2ms
GET /public/module.nmf 304 1ms
GET /public/module.pexe 304 1ms
GET /api/work?poll=true 200 30013ms - 55b
GET /api/work?poll=true 304 30016ms
GET /api/balance 304 1ms
GET /api/work?poll=true 304 30021ms
GET /api/work?poll=true 304 30016ms
GET /api/balance 304 1ms
GET /api/work?poll=true 304 30013ms
GET /api/balance 304 1ms
GET /api/work?poll=true 304 30001ms
GET /api/work?poll=true 304 30030ms
GET /api/balance 304 1ms
GET /api/work?poll=true 304 30003ms
```

**Comment by 7THStage** [comment]
It looks like you're not connecting to a pool. You should see a line like the following when the application receives work to redistribute:

```
[INFO] 2014-02-27T00:14:03.454Z 2139 Got New Work
```

It's always "Warming Up" because it can't get any work from the API. Please check your `stratum` configuration, and make sure the `active` option is set to true.

**Comment by lukespragg** [comment]
Ahhh, always the simple things. It works now!

What is the purpose of the active setting then, just to disable polling for work?

**Comment by 7THStage** [comment]
When I'm developing in node, I use an NPM packaged called `node-dev` that automatically restarts the process whenever a required file changes. If I was connected to a pool during this, it would constantly be disconnecting and reconnecting without ever submitting any work. Pool operators have enough stuff to worry about without me constantly wasting their server resources, and I didn't want to have to comment and uncomment stuff. Thus, an option for the config file was born!

**Comment by lukespragg** [comment]
Makes sense, thanks. :)
