### ISSUE TITLE
Config option to disable withdrawals

### ISSUE THREAD

**Issue by lukespragg** [7THStage/idigdoge#12]
I'm planning on using this for a site idea, but users shouldn't have the option to withdraw, as the mined coins go into a fund. I'm sure this could be done by hacking up the code, I just wanted to pose the idea before jumping head first into the pile.

**Comment by 7THStage** [comment]
On this one, you're gonna have to jump on in. If you want, you can make it all configurable and submit your changes in a pull request. But it's not on my roadmap. Happy coding!

**Comment by lukespragg** [comment]
Figured that'd be the case, but thought I'd ask before stumbling through an unfamiliar language and code. Thanks!
