### ISSUE TITLE
Dogecoins not updating

### ISSUE THREAD

**Issue by valepu** [7THStage/idigdoge#18]
I have set up idigdoge on my server, i have it running on a pool (or at least it looks like so), but i can't get any dogecoins. Even if i keep it running i still see 0 dogecoins.
looking at the site, it seems to be running, but i don't get any dogecoin. Also on my pool dashboard it doesn't seem to be active (though on the log i often see the "Got new Work" message )

**Comment by lukespragg** [comment]
I noticed this as well.

**Comment by 7THStage** [comment]
Do you mean it's not updating on the front end (so the user balances aren't updating) or you're not getting any coins with your pool?

If the first, are you running the payer process?

If the second, is it just you mining? At that rate of 1 KH/S, it will take a long time for you to find a share that can be submitted to your pool, even at a low difficulty.

**Comment by lukespragg** [comment]
Mine the front end does not update the balance at all, and I've let it run for days. On the pool's site, it doesn't even show the miner as connected, but I checked the username and such.

**Comment by valepu** [comment]
Same Here,
The frontend doesn't update, the database is empty and it doesn't even show as a connected miner on the pool, even though from the log it looks like it's working and on the frontend i can see the Khash

**Comment by 7THStage** [comment]
Are both of you running the payer process? And until you submit a share, most pools won't show it.

@valepu When you say the database is empty, is it totally empty? Try a `LLEN shares::user` and then `KEYS`.

**Comment by leadcoin** [comment]
Okay, I have it mining to where it is pulling work from the pool and even generating valid shares being submitted, but when I try to "LRANGE withdraw 0 -1", I too get an "(empty list or set)". "LLEN shares::user" shows an output of "(integer) 13171"

**Comment by 7THStage** [comment]
Since your `LLEN shares::user` value is so high, my guess is that you're not running the `payer.js` process. I believe I need to make that portion of the README clearer, but it is there. The `payer.js` process is what actually credits users with their coins by processing entries in the `shares::user` list.

**Comment by 7THStage** [comment]
Since I haven't heard from the original posters of the issue, I'm going to assume everyone got it all working. :)

**Comment by lukespragg** [comment]
I haven't had any time to play with it lately, so haven't been able to figure out what it's doing. More than likely I'm not running the payer.js as you suggested.

**Comment by valepu** [comment]
I'm in the same situation of Wulfspider but i'm pretty sure this is the problem, i agree it should be made clearer on the readme

**Comment by leadcoin** [comment]
Just run
node payer.js & 
Right? I've done that and I still get "(empty list or set)". LLEN shares::user now returning a result of 0 now, while that's running, though.

**Comment by 7THStage** [comment]
@leadcoin I think you've got this running now, but I'm going to answer anyway.

`LRANGE withdraw 0 -1` won't show any results until someone has made a withdrawal (clicked withdraw, received their link, and entered their address).

`LLEN shares::user` being empty means that it has successfully went through all the pending shares, and should have updated balances appropriately.
