### ISSUE TITLE
Location of email requests to purge?

### ISSUE THREAD

**Issue by leadcoin** [7THStage/idigdoge#20]
In the instance of where someone submits a request for cashout and they never receive an email, is there a list where that information is held? I didn't see that information under the redis-cli commands.

I'd like to clear it so they can resubmit or to be able to troubleshoot why email didn't go out in the first place.

**Comment by 7THStage** [comment]
Each withdrawal is stored as two keys. One connects the withdraw key to the email, the other connects the email to the withdraw key, like so (I shortened the key):

`withdraw::idigdoge@gmail.com = 84e57108`
`withdraw::84e57108 = idigdoge@gmail.com`

If someone didn't get an email, just pop their email address into a `DEL withdraw::idigdoge@gmail.com` command, and they can re-request it (or you can pop onto your site and request it for them).

**Comment by leadcoin** [comment]
Whenever I input that command, though, it crashes the server.

**Comment by 7THStage** [comment]
The `DEL` command? That's... not normal. It crashes Redis, or IDD?

**Comment by leadcoin** [comment]
Oh, yeah, totally. Kills the IDD node dead. Makes it to where if you were pulling up the site in a browser it 404s it.

**Comment by 7THStage** [comment]
That doesn't even make sense. Depending on your settings, perhaps your Redis server has a limited number of connections, and connecting using `redis-cli` kicks the IDD server? That's the only idea I have. Running a command on `redis-cli` shouldn't do anything to the `node` process.

**Comment by leadcoin** [comment]
Well, I checked and reloaded the site when going into redis-cli. It stays up until I put in that DEL command.

Something screwy is going on. I'm probably going to have to start the whole thing over.

**Comment by 7THStage** [comment]
Yeah, that is screwy. I have no ideas as to what could be wrong though. I'd say reinstalling everything would be your best bet. Sorry I couldn't be more help!

**Comment by leadcoin** [comment]
No, that's fine, but I did find something. After going and getting a different email that has never been used on the site before, waited until I had enough to withdraw and then clicked to, it said "server unavailable" and I pulled up my screen in terminal and found this:

http://imgur.com/eSCmWSK

So I checked the withdraw.jade that that is coming from, but it's the same as what you had. Is there somewhere else with that series of messages that I can check where it has "unexpected text"?

**Comment by 7THStage** [comment]
Sorry for the late reply. That exception is what is causing the Node.js process to crash. For a blank line, I think you might have to add a space after the pipe, or something like that. I remember having a similar problem when I built the template. Try the space. :)

**Comment by leadcoin** [comment]
oh. my. god.  

Yeah. That's what it was. Thanks for having a look.

**Comment by Walkman100** [comment]
Talk about technicalities.
