### ISSUE TITLE
Has anyone ever received DOGE

### ISSUE THREAD

**Issue by geopayme** [7THStage/idigdoge#22]
Hello I am curious if anyone on this website: https://www.idigdoge.com/

ever has received any coins... 

Thanks

**Comment by Walkman100** [comment]
I have

**Comment by thenexxuz-zz** [comment]
Yes many, but the thing is this uses YOUR CPU's cycles so if you are using an old computer that is not very powerful it will take a LONG time to generate enough to be able to do a withdrawal.

**Comment by davidawad** [comment]
yes i have,  it works but it takes  longer to generate 1 coin so you'll need some time.

**Comment by geopayme** [comment]
Thanks guys!

I found this service that gives me free coins http://cointellect.com/
http://cointellect.com/?code=a93ac98d
